### ISSUE TITLE
离大谱

### ISSUE THREAD

**Issue by chenyuanxi11** [Molmin/OI#1]
1. 没有data目录和文件，没法自动创建，会报错
2. 配置完成出现神奇特性，大量 undefined，不明白改哪里

**Comment by Molmin** [comment]
This question is simple.

I haven't configured the installation program yet, but you can read the code and configure it yourself.

I will complete this configuration in the future, but I don't have time recently.

**Comment by Molmin** [comment]
This project is written in JavaScript, and improper use can lead to errors. I may use TS refactoring in the future.
